### ISSUE TITLE
Language <select> smushed in Safari

### ISSUE THREAD

**Issue by simevidas** [tomayac/SVGcode#89]
This fixed the issue for me:

```css
select {
  flex-shrink: 0;
}
```

(via https://twitter.com/AmeliasBrain/status/1584195314168508416)

![FfwkuurX0AInYO5](https://user-images.githubusercontent.com/716405/197411765-05e41941-b448-4345-8076-dcfbbe28e45f.jpg)
